### ISSUE TITLE
_decrypt & _encrypt failing test

### ISSUE THREAD

**Issue by Islam2074** [waelio/waelio-utils#3]
**_decrypt & _encrypt failing test**
functions failing tests

**To Reproduce**
```js
 expect(_decrypt(  _encrypt(payloads[index])) ).toEqual(payloads[index])
```

**Expected behavior**
```js
 TRUE
```
**Screenshots**
none

**Comment by peace2074** [comment]
Working on it!
Please report any issues, I'm here ;)
